# **Project 4 Of Machine Learning**
*   in this we are going work on Logistic Regression using titanic dataset

# *Set Up and Data*

1. Importing all the libraries required

In [44]:
# Import all the libraries used in this project
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# To Ignore warnings because aur Project will be in developing state
import warnings
warnings.filterwarnings('ignore')

2. fetch the data

In [45]:
# To create a Project, we need a data, so let's fetch the data
myData=sns.load_dataset('titanic')
myData.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True


# 1. *EDA*

1. Check for the:  
* 1. columns  
* 2. shape of data  
* 3. information of data  
* 4. Description of data 

In [46]:
# 1. columns
myData.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [47]:
# 2. shape of data
myData.shape

(891, 15)

In [48]:
# 3. information of data
myData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB


In [49]:
# Check your data before cleaning
myData

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True


# 2. *Data Cleaning*

In [50]:
# 1. Drop the data which are null
myData.drop(["deck", "embark_town", "alive", "class", "who", "adult_male"], axis=1, inplace=True)


In [51]:
#  Again check your data after cleaning
myData

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.0,1,0,7.2500,S,False
1,1,1,female,38.0,1,0,71.2833,C,False
2,1,3,female,26.0,0,0,7.9250,S,True
3,1,1,female,35.0,1,0,53.1000,S,False
4,0,3,male,35.0,0,0,8.0500,S,True
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,True
887,1,1,female,19.0,0,0,30.0000,S,True
888,0,3,female,NaN,1,2,23.4500,S,False
889,1,1,male,26.0,0,0,30.0000,C,True


In [52]:
# information of data again check
myData.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  891 non-null    int64  
 1   pclass    891 non-null    int64  
 2   sex       891 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64  
 5   parch     891 non-null    int64  
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     891 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB


In [53]:
# 2. fill the null values with mean median and mode
myData["age"].fillna(myData["age"].mean(), inplace=True)



In [54]:
# delete the rows which are null
myData.dropna(subset=["embarked"], inplace=True)

In [55]:
#  again check the null values
myData.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  889 non-null    int64  
 1   pclass    889 non-null    int64  
 2   sex       889 non-null    object 
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64  
 5   parch     889 non-null    int64  
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object 
 8   alone     889 non-null    bool   
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB


# 3. *Label Encoding*

In [56]:
# import the label encoder
from sklearn.preprocessing import LabelEncoder
myLabEncObject = LabelEncoder()

In [57]:
myData.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,male,22.0,1,0,7.2500,S,False
1,1,1,female,38.0,1,0,71.2833,C,False
2,1,3,female,26.0,0,0,7.9250,S,True
3,1,1,female,35.0,1,0,53.1000,S,False
4,0,3,male,35.0,0,0,8.0500,S,True


**1. Sex, Embarked Values are only in numeric**
* Label encode it

In [58]:
myData['sex'] = myLabEncObject.fit_transform(myData['sex'])
myData["embarked"] = myLabEncObject.fit_transform(myData["embarked"]) # S=2, C=0, Q=1

In [59]:
myData

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,1,22.000000,1,0,7.2500,2,False
1,1,1,0,38.000000,1,0,71.2833,0,False
2,1,3,0,26.000000,0,0,7.9250,2,True
3,1,1,0,35.000000,1,0,53.1000,2,False
4,0,3,1,35.000000,0,0,8.0500,2,True
...,...,...,...,...,...,...,...,...,...
886,0,2,1,27.000000,0,0,13.0000,2,True
887,1,1,0,19.000000,0,0,30.0000,2,True
888,0,3,0,29.699118,1,2,23.4500,2,False
889,1,1,1,26.000000,0,0,30.0000,0,True


* Now convert rest value of ALONE true false into 1 and 0

In [60]:
myData=myData.astype(int)


In [61]:
myData

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,1,22,1,0,7,2,0
1,1,1,0,38,1,0,71,0,0
2,1,3,0,26,0,0,7,2,1
3,1,1,0,35,1,0,53,2,0
4,0,3,1,35,0,0,8,2,1
...,...,...,...,...,...,...,...,...,...
886,0,2,1,27,0,0,13,2,1
887,1,1,0,19,0,0,30,2,1
888,0,3,0,29,1,2,23,2,0
889,1,1,1,26,0,0,30,0,1


# 4. *Logistic Regression and its Model*

**1. Selecting the variables**
* 1. x=Input Variable- all except survived
* 2. y=Output Variable- those who survived

In [62]:
xInput = myData.drop("survived", axis=1)
yOutput = myData["survived"]

**2. Train Test Split**

In [63]:
from sklearn.model_selection import train_test_split

xTrain, xTest, yTrain, yTest = train_test_split(xInput, yOutput, test_size=0.2, random_state=42)

**3. Logistic Model Creation**

In [64]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

# fit the modelto train it
model.fit(xTrain,yTrain)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


**4. Prediction: The predicted y data**

In [65]:
yPred = model.predict(xTest)
yPred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

**4. Y-Test : The real data**

In [66]:
yTest

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: survived, Length: 178, dtype: int64

# **Model Evaluation**

**Here we will use Confusion matrix**  
**as same we were using r2 and adjusted r2 in Linear regression**

In [67]:
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report

**1. accuracy score**

In [68]:
accuracy_score(yTest,yPred)

0.8033707865168539

**2. Confusion matrix**

In [69]:
confusion_matrix(yTest,yPred)

array([[90, 19],
       [16, 53]])

**3. Now print classification report which will contain all the reports**

In [70]:
print(classification_report(yTest,yPred))

              precision    recall  f1-score   support

           0       0.85      0.83      0.84       109
           1       0.74      0.77      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.80      0.80       178



In [71]:
myData

,survived,pclass,sex,age,sibsp,parch,fare,embarked,alone
0,0,3,1,22,1,0,7,2,0
1,1,1,0,38,1,0,71,0,0
2,1,3,0,26,0,0,7,2,1
3,1,1,0,35,1,0,53,2,0
4,0,3,1,35,0,0,8,2,1
...,...,...,...,...,...,...,...,...,...
886,0,2,1,27,0,0,13,2,1
887,1,1,0,19,0,0,30,2,1
888,0,3,0,29,1,2,23,2,0
889,1,1,1,26,0,0,30,0,1


# 5. *KNN Algorithm and its model*

Before using KNN, we will need to do feature scaling because, here AGE and FARE values are higher which may impact the prediciton

**1. Feature Scaling**

In [72]:
from sklearn.preprocessing import StandardScaler
# initializing the object to use its functions
myScaler = StandardScaler()

In [73]:
#  now scale the trained data and testing data
xTrainScaled = myScaler.fit_transform(xTrain)
xTestScaled = myScaler.fit_transform(xTest)

**2. Now import KNN Algo**

In [74]:
from sklearn.neighbors import KNeighborsClassifier

# now start the object and put k value =5
knnModel = KNeighborsClassifier(n_neighbors= 5)
#  now train the model on xTrainScaled and yTrain
knnModel.fit(xTrainScaled,yTrain)

,n_neighbors,5
,weights,'uniform'
,algorithm,'auto'
,leaf_size,30
,p,2
,metric,'minkowski'
,metric_params,None
,n_jobs,None


**3. Y Predcition**

In [75]:
# now see the knn prediction
yPredKnn = knnModel.predict(xTestScaled)

In [76]:
yPredKnn

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

**4. ACCURACY SCORE**

In [77]:
accuracy_score(yTest,yPredKnn)

0.7808988764044944

**5. CONFUSION MATRIX**

In [78]:
confusion_matrix(yTest,yPredKnn)

array([[90, 19],
       [20, 49]])

**6. Classification Report**

In [ ]:
print(classification_report(yTest,yPredKnn))

# 6. *Naive Bayes Theorem*

In [81]:
#  import the library
from sklearn.naive_bayes import GaussianNB

# while using the naive bayes we do not generallly use standard scaling

#  initialize the object
modelNaive = GaussianNB()

# Training and loading the data
modelNaive.fit(xTrain, yTrain)

,priors,None
,var_smoothing,1e-09


**1. Y prediction**

In [84]:
yPredNaive = modelNaive.predict(xTest)
yPredNaive

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

**2. Accuracy Score**

In [86]:
accuracy_score(yTest,yPredNaive)

0.7752808988764045

**3. Confusin Matrix**

In [87]:
confusion_matrix(yTest,yPredNaive)

array([[84, 25],
       [15, 54]])

**4. Classification Report**

In [89]:
print(classification_report(yTest,yPredNaive))

              precision    recall  f1-score   support

           0       0.85      0.77      0.81       109
           1       0.68      0.78      0.73        69

    accuracy                           0.78       178
   macro avg       0.77      0.78      0.77       178
weighted avg       0.78      0.78      0.78       178



# *7. Decision Tree*

In [92]:
#  import the library
from sklearn.tree import DecisionTreeClassifier
#  initialize the object
modelDecision = DecisionTreeClassifier(random_state=42)

# Training and loading the data
modelDecision.fit(xTrainScaled,yTrain)


# we have to do feature scaling at first for this, so we will use X Train Scaled value and YTrain

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


**1. Y prediction**

In [94]:
yPredDecision = modelDecision.predict(xTestScaled)
yPredDecision

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0])

**2. Accuracy Score**

In [96]:
accuracy_score(yTest,yPredDecision)

0.7696629213483146

**3. Confusin Matrix**

In [97]:
confusion_matrix(yTest,yPredDecision)

array([[88, 21],
       [20, 49]])

**4. Classification Report**

In [98]:
print(classification_report(yTest,yPredDecision))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81       109
           1       0.70      0.71      0.71        69

    accuracy                           0.77       178
   macro avg       0.76      0.76      0.76       178
weighted avg       0.77      0.77      0.77       178



# *9. SVM*

In [99]:
#  import the library
from sklearn.svm import SVC
#  initialize the object
modelSVM = SVC(kernel = 'linear')

# Training and loading the data
modelSVM.fit(xTrainScaled,yTrain)


# we have to do feature scaling at first for this, so we will use X Train Scaled value and YTrain

,C,1.0
,kernel,'linear'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,False
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


**1. Y prediction**

In [100]:
yPredSVM = modelSVM.predict(xTestScaled)
yPredSVM

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1])

**2. Accuracy Score**

In [101]:
accuracy_score(yTest,yPredSVM)

0.8033707865168539

**3. Confusin Matrix**

In [102]:
confusion_matrix(yTest,yPredSVM)

array([[91, 18],
       [17, 52]])

**4. Classification Report**

In [103]:
print(classification_report(yTest,yPredSVM))

              precision    recall  f1-score   support

           0       0.84      0.83      0.84       109
           1       0.74      0.75      0.75        69

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

